### ISSUE TITLE
Could not resolve dependencies for project cyclehunter

### ISSUE THREAD

**Issue by pije76** [rluu/cyclehunter#1]
When I run mvn package, it give me error:
"Could not resolve dependencies for project cyclehunter:com.ryanluu.cyclehunter:jar:1.0-SNAPSHOT: Could not find artifact swisseph:swisseph:jar:2.00.00 in central (https://repo.maven.apache.org/maven2)"

Any fix for this? Thanks in advanced.

**Comment by rluu** [comment]
Hi pije76, 
Thank you for your interest in my project.  The artifact you speak of is not on maven, but you can add it to your local maven manually by first downloading it from this website:  
http://th-mack.de/download/index.html

I would also like to let you know that this project is in the pre-alpha stages, and there is not much functionality available.  Additionally, there has not been any recent development on it and I don't know if or when I will continue development.  I'll put this project into 'archive', so that it's more obvious others.
